// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PasswordManager.Models;

#nullable disable

namespace PasswordManager.Migrations
{
    [DbContext(typeof(AccountContext))]
    [Migration("20260220031556_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntrySecurityQuestion", b =>
                {
                    b.Property<int>("EntriesEntryId")
                        .HasColumnType("int");

                    b.Property<int>("SecurityQuestionsSecurityQuestionId")
                        .HasColumnType("int");

                    b.HasKey("EntriesEntryId", "SecurityQuestionsSecurityQuestionId");

                    b.HasIndex("SecurityQuestionsSecurityQuestionId");

                    b.ToTable("EntrySecurityQuestion", (string)null);
                });

            modelBuilder.Entity("PasswordManager.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("MasterPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            MasterPassword = "testPassword123",
                            Username = "testUser"
                        },
                        new
                        {
                            AccountId = 2,
                            MasterPassword = "anotherpassword!",
                            Username = "SecondUser"
                        });
                });

            modelBuilder.Entity("PasswordManager.Models.Entry", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntryId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntryId");

                    b.HasIndex("AccountId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("PasswordManager.Models.SecurityQuestion", b =>
                {
                    b.Property<int>("SecurityQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SecurityQuestionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SecurityQuestionId");

                    b.HasIndex("AccountId");

                    b.ToTable("SecurityQuestions");
                });

            modelBuilder.Entity("EntrySecurityQuestion", b =>
                {
                    b.HasOne("PasswordManager.Models.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntriesEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasswordManager.Models.SecurityQuestion", null)
                        .WithMany()
                        .HasForeignKey("SecurityQuestionsSecurityQuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PasswordManager.Models.Entry", b =>
                {
                    b.HasOne("PasswordManager.Models.Account", "Account")
                        .WithMany("Entries")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PasswordManager.Models.SecurityQuestion", b =>
                {
                    b.HasOne("PasswordManager.Models.Account", "Account")
                        .WithMany("SecurityQuestions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PasswordManager.Models.Account", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("SecurityQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
